- src/Unsafe/Linear.hs
"castLinear" was renamed to "toLinear" but comments were still referring
to the function as "castLinear".
> rename castLinear in comments too

- .circleci/config.yml
- stack.yaml
Partly for better CI caching. Partly because I won't need to add swaths of `extra-deps`.
This requires stack 1.6.1. Therefore, I pushed a new linear-types image with the newer stack in it.
> Stack: use a snapshot

- examples/Foreign/List.hs
- examples/Spec.hs
- linear-base.cabal
- src/Foreign/Marshal/Pure.hs
_Depends on #8 . There is only one commit in this PR._
Memory is freed in case of exception. A list of pointers is kept in a
non-gc'd region in order not to add to the GC pressure, and not
contribute to less predictable latencies.
> Manually managed data: make exception safe

- examples/Foreign/Heap.hs
- examples/Foreign/List.hs
- examples/Spec.hs
- linear-base.cabal
- src/Foreign/Marshal/Pure.hs
This proposes an interface for pure off-heap data which doesn't expose a `Storable` constraint.
Instead, it defines a ground truth abstract type class `KnownRepresentable`. Which holds at basic types, tuples, and `Maybe`.
The `Foreign.Marshal.Pure` primitives are relativised with a `Representable` constraints. To implement representable, one must provide a retraction to `KnownRepresentable` (a helper type class `MkRepresentable` helps make it more modular).
This is an ok interface. But it yield slightly ugly memory-representation for sum types. (as `Either a b` would be represented as `(Word8, Maybe a, Maybe b)`. So I want to change it for a better representation later. But this is still better than `Storable`: instances are safe to define on the user side.
> Foreign.Marshal.Pure without Storable

- src/System/IO/Linear.hs
It is necessary with the new specification which doesn't auto η-expand anymore.
> η-expand a linear function used as an unrestricted one

- examples/Spec.hs
- linear-base.cabal
- src/Control/Monad/Builder.hs
- src/Control/Monad/Linear.hs
- src/Control/Monad/Linear/Builder.hs
- src/Foreign/Marshal/Pure.hs
- src/Prelude/Linear.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource.hs
This PR adds a linear (enriched) monad hierarchy.
Highlights:
- The linear monad hiearchy is in its own module, in order to reuse the same notations as regular monads, in particular the infix notations. Defining instance feels quite native this way.
- I put the entire functor/applicative/monad/monad-fail hierarchy in the same module (`Control.Monad.Linear`). This is unlike the usual hierarchy which has one module per type-class. We could want to instead follow the same module layout as `base` (except that this kind of enriched functors should be in `Control.Functor.Linear`, `Data.Functor.Linear` will have a different type). I decided this way because they are generally used together (an alternative is to define them in separate files and re-export the preceding modules)
- This uses …
> A linear monad hierarchy

- examples/Foreign/List.hs
- linear-base.cabal
- src/Control/Monad/Linear.hs
- src/Data/Functor/Linear.hs
- src/Data/Vector/Linear.hs
- src/Foreign/Marshal/Pure.hs
- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal/Simple.hs
This comes in three part
- A data-functor hierarchy representing containers (especially a `Data.Applicative` which represents zippable things)
- Vectors of known length, which are `Data.Applicative`
- An `Dupable`'s one method now has type `KnownNat n => a ->. V n a`.
Here is the rationale
> One immediate benefit is that the instances are much easier to write, using the applicative instance (of course, it would have worked just fine, if that was the only goal, to make a V2 applicative functor).
>
> The other benefit is that there was no pleasant way to produce more than two things from a dupable. It is possible to write a function `(a ->. (a,a)) ->. a ->. V n a`, but at this point we already have `V n` defined. And producing a `V n a` directly is, I expect, significantly more efficient.
> …
> Vectors of known length & refreshed Dupable

- src/Control/Monad/Linear.hs
- src/Data/Functor/Linear.hs
Added some minimal pragmas as in standard base to allow alternate definition of Applicative. Added default definition of `(>>)`.
> Define Applicatives by `liftA2` and add default (>>)

- src/Data/Functor/Linear.hs
- src/Data/Vector/Linear.hs
- src/Prelude/Linear.hs
Modify Data.Traversable to use Data.Applicatives and use this to write cleaner `Dupable a => Dupable [a]` and same for `Movable`.
> Traversable changes

- src/Control/Monad/Linear.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource.hs
Define `ap` for Control.Monad so Control.Applicative instances can be defined conveniently.
> Add `ap` as convenience operator for Control.Monad

- linear-base.cabal
- src/Control/Monad/Linear.hs
- src/Data/Bifunctor/Linear.hs
- src/Data/Profunctor/Linear.hs
- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal/Simple.hs
Basic profunctor classes
Replaces part of #35, with a cleaner history. Only includes profunctor classes and no lenses.
> Profunctors

- src/Data/Bifunctor/Linear.hs
Use the linear `either` consumer to have nicer `Either` instances
> Use either combinator to simplify instances

- src/Data/Monoid/Linear.hs
Add a deriving via combinator for Prelude.Semigroup given Linear.Semigroup, and similar for Monoid.
> Deriving Via combinator for Semigroup/Monoid

- src/Data/Bifunctor/Linear.hs
- src/Data/Profunctor/Kleisli/Linear.hs
For ghc-8.9.0.20190613, there is a bug in linearity checking (see also discussion in #43 
https://github.com/tweag/ghc/issues/380
This introduces a temporary fix so that linear-base compiles.
> Temporary patch to workaround #380 in linear ghc

- src/Data/Array/Polarized/Pull/Internal.hs
- src/Data/Array/Polarized/Push.hs
Tiny fix to simplify instances for Prelude Semigroups
> Use deriving via for Prelude Semigroup instances

- linear-base.cabal
- src/Control/Monad/Linear.hs
- src/Control/Monad/Linear/Internal.hs
- src/Data/Functor/Linear.hs
- src/Data/Functor/Linear/Internal.hs
- src/Data/Functor/Linear/Internal/Traversable.hs
- src/Data/Unrestricted/Linear.hs
- src/Prelude/Linear.hs
Created `Control.Monad.Linear.Internal`, and moved the majority of `Control.Monad.Linear` there.
This makes it possible to put `<$` in `Control.Monad.Linear`, since there is a different data version which may also be useful:
```haskell
(<$) :: (Functor f, Consumable b) => a -> f b ->. f a
```
for instance to replace every element of a list, one can use `3 Data.<$ [True, False, True]`.
(@facundominguez this may mean your use of `<$` for Control Functors needs to be adjusted to Linear.<$, if you import Control.Monad.Linear as Linear).
Also adds Functor/Monad instances for some standard monad transformers from `transformers`, where appropriate, but the transformers are not re-exported.
> Transformer instances

- src/Data/Num/Linear.hs
Add newtypes to give the underlying monoids of Additive and Multiplicative, as linear versions of Sum and Product.
> Underlying monoids for Additive and Multiplicative

- src/Data/Array/Polarized/Push.hs
- src/Data/Functor/Linear/Internal.hs
Fixed some typos, and added that Applicatives should be _non-empty_ fixed size containers.
> Some typo fixes

- src/Control/Monad/Linear/Internal.hs
- src/Data/Unrestricted/Linear.hs
A couple of basic functor/applicative/monad instances for `(,) a` and `Unrestricted`
> More instances

- examples/Simple/TopSort.hs
- linear-base.cabal
- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
Rewrote hashmaps in a much better style with an empty constructor and fixed several deep and confusing bugs.
Fixes #118
> Rewriting hashmap implementation for correctness

- src/Data/Array/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
This patch fixes an issue where using a previously read value from an array in a write causing an infinite loop.
Here is an example:
```haskell
{-# LANGUAGE LinearTypes #-}
module Main where
import Data.Function ((&))
import qualified Prelude.Linear as L
import qualified Data.Array.Mutable.Linear as Array
import Prelude.Linear (Unrestricted(..))
processArr :: Array.Array () #-> Unrestricted ()
processArr arr =
Array.read arr 0 L.& \(arr', Unrestricted before) ->
Array.write arr' 0 (before `seq` ()) L.& \arr'' ->
Array.read arr'' 0 L.& \(arr''', after) ->
arr''' `L.lseq` after
main :: IO ()
main =
Array.fromList [()] processArr
& \(Unrestricted a) -> print a
```
The `seq` call there is just to explicitly show the dependency. I found this issue while writing a bigger application where I was …
> Fix a laziness bug on Data.Array.Mutable.Linear

- src/Data/Array/Mutable/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Unsafe/MutableArray.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
Closes #142.
This PR changes wraps the result of `Unsafe.MutableArray.read` with an
unboxed tuple, so the array lookup can be evaluated without evaluating
the result.
Because of that, now `Data.{Array,Vector}.Mutable.Linear.read` functions
does not unnecessarily force the return value.
I added a test case about strictness issue just for `Array`'s. Because
Vector's `read` function returns the result linearly as opposed to
`Array` which wraps it with an `Unrestricted`. I think this is another
error, so I'll fix that with a separate PR:
```
read :: HasCallStack => Vector a #-> Int -> (Vector a, a)
read :: HasCallStack => Array a #-> Int -> (Array a, Unrestricted a)
```
---
While implementing this, I also noticed that the issue fixed in #135 also applies
to vectors, so this PR also fixes that …
> Make {Array,Vector}.Mutable.Linear lazier

- examples/Simple/TopSort.hs
- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
Closes #150 .
This PR generalizes the collection allocation functions where we delimit the scope of the linear collection with a continuation by consuming the continuation linearly. This allows nesting those continuations. See #150 for an example where the previous signature fails.
While doing this change, I had to inline a few functions to make the typechecker checker happy, although I am not 100% sure why they did not work as-is. However, I hope those changes are not a big deal.
Another noteworthy issue is about the partial functions. Most allocation functions are partial, they panic on things like negative sizes. In those cases, we now can not simply ignore the continuation. So, I am doing this ugly trick in a few places:
```haskell
alloc :: HasCallStack => Int -> a -> (Array a #-> …
```
> Consume the continuation linearly when allocating linear collections

- README.md
- docs/DESIGN.md
- docs/USER_GUIDE.md
- replaced the word "tools", which has little to no precedent, with
"definitions" or "abstractions",
- use relative links where possible,
- remove sections with low information,
- fix license link,
- consistent indentation,
- consistent headings and capitalization.
> Edit pass on documentation

- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Vector.hs
Mutable arrays and vectors are linear on the collection itself, not on the values. So, after we read a value it should be unrestricted. Returning the elements linearly restricts their usage unnecessarily, especially when the elements are not `Movable`.
Before:
```haskell
toList :: Array a #-> (Array a, [a])
read :: HasCallStack => Vector a #-> Int -> (Vector a, a)
```
After:
```haskell
toList :: Array a #-> (Array a, Unrestricted [a])
read :: HasCallStack => Vector a #-> Int -> (Vector a, Unrestricted a)
```
The rest of the PR is pretty much following the types. I decided to create a PR because the change was small. Happy to close it if there is a good reason for keeping the old behaviour.
> Use Unrestricted on Array.toList and Vector.read

- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Unsafe/MutableArray.hs
- test/Test/Data/Mutable/Array.hs
Closes #148.
This PR modifies the resize function on linear arrays to 
* Copy over the elements to the new array instead of returning a constant array
* Support shrinking
In order to provide the same abilities, it also introduces an `allocBeside` function for allocating a new array without a continuation using another array as a uniqueness proof.
See #148 for more details.
> Reimplement resize and resizeSeed functions on linear arrays

- test/Test/Data/Mutable/Array.hs
It looks like merging #152 and #154  at the same time caused the master fail to typecheck. I'll make sure that the branches are up-to-date before merging from now on.
> Fix build error caused by conflicting changes

- README.md
> Fix url to linear-types tag on Tweag's blog

- linear-base.cabal
- src/Debug/Trace/Linear.hs
Closes #171.
This module implements a linear version of `Debug.Trace`.
It is implemented as a thin wrapper, it mostly uses `Unsafe.Linear.toLinear` to coerce the non-linear functions.
It uses linear arrows wherever possible, however we can't do that some places because we do not have a linear version of 'Show'. It also translates functions using `Prelude.IO` and `Prelude.Applicative` to use the linear IO and the linear data applicative respectively.
I also copied over one-line summaries of the functions from the original module, but decided against copying over the whole documentation; just because it felt like that it too much duplication. Let me know if prefer having the whole documentation, and I can copy the rest over.
> Implement Debug.Trace.Linear

- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
This PR implements mutable vectors in terms of mutable arrays; removing the duplicated logic and some unsafe calls. The existing tests pass, and the module still provides the same interface.
Here are the major changes:
* Mutable arrays now expose `readUnsafe` and `writeUnsafe` functions which omit bounds-checking.
* Mutable vectors now only store their size instead of a tuple of `(size, capacity)`. The `capacity` now can be obtained from the size of the underlying array.
Closes https://github.com/tweag/linear-base/issues/144. Also, a prerequisite of https://github.com/tweag/linear-base/issues/165.
> Implement mutable vectors using arrays

- docs/DESIGN.md
- docs/USER_GUIDE.md
- examples/Foreign/Heap.hs
- examples/Simple/FileIO.hs
- examples/Simple/TopSort.hs
- examples/Spec.hs
- src/Data/Array/Mutable/Linear.hs
- src/Data/Eq/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Num/Linear.hs
- src/Data/Ord/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Unrestricted/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Foreign/Marshal/Pure.hs
- src/Prelude/Linear.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
- test/Test/Data/Mutable/Vector.hs
This PR renames `Unrestricted` to `Ur` and closes #131. 
The discussion of how we arrived at this name is documented in the issue. Basically, `Unrestricted` is a really good name but too long. Since this data type is so fundamental to linear programming that any user will quickly become familiar with its definition, it's sensible to keep the name short for line length.
Remarks:
- In the spirit of keeping things short, I've changed qualified imports that were `Unrestricted` to `Ur`. Is this problematic or can we allow it since it will be so common? (I'm leaning towards the latter.)
- `unUnrestricted` has been renamed to `unUr`
> Renamed Unrestricted to Ur

- src/Data/Array/Mutable/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
- test/Test/Data/Mutable/Vector.hs
Closes https://github.com/tweag/linear-base/issues/175.
This PR wraps the return value of `size` and `member` functions  across the linear mutable collections with `Unrestricted`. The issue linked above has the details.
If #178 is merged before this one, I'd be happy to rename `Unrestricted` with `Ur`, should be simple.
> Make 'size' and 'member' functions return Unrestricted values

- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
Depends on #179. As part of #165,
It turns out, there is two different flavours of `toList` functions.
* 'toList' returns a new list alongside with the array. In order to do that, it has to read the entire array before returning; this can not done lazily since the underlying mutable array might change.
* 'toListLazy' converts an array to a lazy list, consuming the array in the process. It can do it lazily, since it does not give the array back, therefore guaranteeing in won't be changed.
Vector's 'toList' and 'toListLazy' functions also have the same constraint above.
In order to implement the vector changes, it also adds `unsafeRead` and `unsafeWrite` functions to the vector interface.
>  Implement toList and toListLazy for mutable arrays and vectors 

- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Unsafe/MutableArray.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
Depends on #180,  As part of #165.
Previously, vectors could only grow. This PR adds functions around resizing and slicing vectors and arrays.
* Adds a `pop` function, and renames `snoc` to `push`, just because it sounds more natural to me than `unsnoc`. Happy to revert this change if you prefer the former.
* Adds `slice` functions to arrays and vectors that can return a sub-range of elements.
* Adds a `shrinkToFit` function to vectors to reduce the capacity of a vector.
Alongside with tests for each, of course.
> Add ability to shrink/slice vectors and arrays

- cabal.project
- stack.yaml
Just a small housekeeping PR.
This PR also updates the QuickCheck fork we're using, since the previous PR we're using (https://github.com/nick8325/quickcheck/pull/311) are closed in favour of this one (https://github.com/nick8325/quickcheck/pull/314).
> Update stackage resolver

- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
Depends on #181, As part of #165.
This PR adds a (data) `Functor` instance for mutable arrays and vectors. The `fmap` implementation for both instances do in-place updates (yay linear types). Internal implementation does `unsafeCoerce`, but hopefully it is simple enough, and there's test coverage.
It also adds a `Semigroup` instance for `Vector`'s, where `mappend` tries not to allocate a new vector when there is enough space available.
> Implement Functor and Semigroup instances for mutable vectors and arrays

- examples/Simple/TopSort.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- test/Test/Data/Mutable/HashMap.hs
This PR (hopefully objectively) improves HashMap's internals so that our planned improvements on #164 can be implemented with less changes to the code.
It has three standalone changes each have a separate commit. Unfortunately they all change the same area of the code, so I decided to create a single commit instead of having to solve merge conflicts next. But, ideally, you should be able to review each PR (from older to newer) relatively independently.
The commits have detailed messages about the changes. The only API change is removing the `Size` wrapper which only affects the `empty` function, without causing any behaviour change.
The same tests still pass, but it is a tricky piece of code and I am not 100% sure about the correctness yet. I will spend some time on adding some more tests …
> Internal HashMap improvements

- src/Data/Profunctor/Kleisli/Linear.hs
- src/Data/Profunctor/Linear.hs
These are ported from #79 where they were needed for traversal-type
things. These instances can't hurt. Even though I don't know what we
are going to do with traversals yet.
> Instances for `Monoidal (,) ()`

- .buildkite/pipeline.yml
- cabal.project
Currently, our `stack` builds are failing, throwing errors like:
```
...
2020-09-22 15:05:03.459163: [debug] Failed to decode module interface:
/home/utdemir/workspace/github.com/tweag/linear-base6/.stack-work/dist/x86_64-linux-nix/Cabal-3.3.0.0/build/Data/Vector/Linear.hi
Decoding failure: not enough bytes
2020-09-22 15:05:03.459245: [debug] Failed to decode module interface:
/home/utdemir/workspace/github.com/tweag/linear-base6/.stack-work/dist/x86_64-linux-nix/Cabal-3.3.0.0/build/Data/Vector/Mutable/Linear.hi
Decoding failure: not enough bytes
2020-09-22 15:05:03.459334: [debug] Finished with exception in 18ms: getPackageFiles /home/utdemir/workspace/github.com/tweag/linear-base6/linear-base.cabal
Exception thrown: Prelude.chr: bad argument: 942814208
2020-09-22 15:05:03.459729: …
```
> Replace Stack with cabal-install on CI

- src/Control/Optics/Linear/Internal.hs
- src/Data/Functor/Linear/Internal.hs
A handful of utilities for linear lens.
These are ported from #79 .
> Linear lens combinators

- src/Data/Unrestricted/Linear.hs
- src/Data/Vector/Linear.hs
- src/Prelude/Linear.hs
Closes #151 .
Even though `dupV` should be a better choice in the long term (after we address https://github.com/tweag/linear-base/issues/151#issuecomment-690130887), since our lenght-indexed vector interface is not easy-to-use this PR adds `dup2` to `Dupable` typeclass; with a `{-# MINIMAL dupV | dup2 #-}` pragma.
In order to do that it adds a bounded `iterate` function to length-indexed vectors, and exposes the `caseNat` utility.
In the `iterate` function, there is an `unsafeCoerce` to simplify a small equation. It should be possible to prove that equation from smaller axioms, but I did not see much advantage for this function.
> Add 'dup2' to 'Dupable' class

- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Unrestricted/Linear.hs
- src/Data/Vector/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Prelude/Linear.hs
- test/Test/Data/Mutable/Array.hs
Depends on #203, closes #165.
This PR implements `Dupable` instances for mutable arrays, vectors, hashmaps and sets.
It also adds a `dup2` function to unlifted mutable arrays, since we can not implement `Dupable` for unlifted types.
All the work is done by `GHC.Exts.cloneMutableArray#` through our unlifted arrays, and pretty much all other instances are implemented trivially by using `Dupable` instances of their contents.
> Implement Dupable instances for mutable collections

- linear-base.cabal
- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/Vector.hs
As suggested in https://github.com/tweag/linear-base/pull/180#issuecomment-694047048, this PR adds a constant time `freeze` method to unlifted and lifted mutable arrays and mutable vectors.
As usual, it is implemented with unsafe primitives in unlifted arrays, and the rest of the collections make use of that implementation. I hope I got the `MVector`'s parameters right, as far as I could understand its first parameter is the starting index and the second index is the length. Because of that starting index, we can not have a constant time `thaw` operation (which would be unsafe anyway).
I am not entirely sure about the name `freeze`. I was also thinking of names like `toVector` or `toImmutableVector`, but they are likelier to be confused with either of our `Vector`'s. Let me know if you …
> Add a constant time 'freeze' function to mutable arrays and vectors

- examples/Simple/TopSort.hs
- linear-base.cabal
- src/Control/Monad/Linear/Internal.hs
- src/Data/List/Linear.hs
- src/Data/Unrestricted/Linear.hs
- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal.hs
Closes #170, discussion at #126 .
This PR adds linear versions of the majority of Data.List and Data.Foldable functions, specializing them to work on lists. Most of them are implemented by unsafe coerces, and the ones requiring `Consumable` or `Dupable` typeclasses reimplemented. I hope I got the casts right (meaning, they aren't omitting or duplicating any elements without using the required typeclasses).
I also omitted a few methods from `Data.List`, if they
* work on infinite lists, eg: `iterate`, `repeat`.
* discard most of the elements, eg: `head`, `find`, `null` (or they require significant changes on the type signatures)
* are partial, eg: `scan1`, `foldl1`
The latter two points are arbitrary decisions on my part, so let me know if you disagree and I can add them back. In my …
> Implement Data.List.Linear

- linear-base.cabal
- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- test/Test/Data/Mutable/HashMap.hs
Closes #164 .
This PR expands HashMap interface with following main functionalities:
* An `alter` function which can be used to delete, insert or update keys.
* A `mapMaybe` function which can transform the HashMap optionally throwing out the elements.
Most of the rest of the changes are implemented in terms of the above functions.
* `mapMaybe` provides the `Functor` instance and `filter`-like functions
* `alter` provides `union` and `intersection` functions, which in turn becomes the `Semigroup` instance.
While implementing above changes, I had to add a `map` function to `Array`'s; because the `Functor` instance was overly restrictive:
```haskell
fmap :: (a #-> b) -> Array a #-> Array b
map  :: (a  -> b) -> Array a #-> Array b
```
Since the `Array` does not store linear values, the new …
> Expand linear mutable HashMap interface

- examples/Spec.hs
- src/Control/Optics/Linear/Internal.hs
- src/Data/Array/Destination.hs
- src/Data/Array/Polarized/Pull/Internal.hs
- src/Data/Array/Polarized/Push.hs
- src/Data/Bool/Linear.hs
- src/Data/Either/Linear.hs
- src/Data/Eq/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/List/Linear.hs
- src/Data/Maybe/Linear.hs
- src/Data/Monoid/Linear.hs
- src/Data/Ord/Linear.hs
- src/Data/Tuple/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Foreign/Marshal/Pure.hs
- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource.hs
Closes #172, relevant discussion: https://github.com/tweag/linear-base/pull/133#issuecomment-679234955
This PR modifies `Prelude.Linear` to not export `module Prelude`, but replaces it with explicit re-exports.
I tried to keep the interface the same; but I found some linear implementations we could export instead of the unrestricted counterparts:
* We now export `Data.Eq.Linear` and `Data.Ord.Linear`, instead of exporting unrestricted equality and comparision functions.
* We now export linear versions of `fst` and `snd` instead of unrestricted ones from the `base`.
Also:
* We don't export any `Functor`s, because it isn't clear whether data or control `Functor`'s should be exported. However, we do export unrestricted `IO` instead of linear `IO`.
* I added `Maybe`, `Either` and `Ordering` …
> Explicit Prelude.Linear re-exports

- src/Data/Profunctor/Kleisli/Linear.hs
- src/Data/Profunctor/Linear.hs
Mostly because we can.
I'm not sure if any of these are useful. Or the `Monoidal (,) ()` instance for that matter. Both are increasingly looking like they are an artifact of the past.
Though if we want a linear equivalent to arrows, we may need at least the `Monoidal (,) ()`.
So, anyway, it's exploratory, but can't hurt.
> Profunctor.Monoidal Either Void instances

- linear-base.cabal
- src/Control/Optics/Linear.hs
- src/Control/Optics/Linear/Iso.hs
- src/Control/Optics/Linear/Lens.hs
- src/Control/Optics/Linear/Prism.hs
- src/Control/Optics/Linear/Traversal.hs
I followed the structure of the lens library: functions are
re-exported in modules which focus on one particular optics. So one
can see what the most relevant operations are for specific
optics. Everything is then re-exported in one big
Control.Optics.Linear module.
Closes #137 .
> Export optics

- linear-base.cabal
- src/Data/Unrestricted/Linear.hs
- src/Data/V/Linear.hs
Closes #207.
As discussed in #207, this patch changes our vector-of-known-length module name from `Data.Vector.Linear` to `Data.V.Linear`.
> Rename Data.Vector.Linear to Data.V.Linear

- src/Data/Array/Mutable/Linear.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource.hs
I saw a few type errors on the inline examples, and fixed them; sometimes with slight stylistic modifications. We should use something like `doctest` to ensure that they do not get out-of-sync with the code. I'll create an issue.
This also adds a new export to `System.Resource.Linear` to ensure that the `openFile` method there can be used without importing `System.IO` too. This removes an import from an example.
> Fix type errors on inline examples

- examples/Simple/TopSort.hs
- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/List/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
- test/Test/Data/Mutable/Vector.hs
Closes #191 .
This PR flips the returned tuples at linear mutable collections, so the "actual" return value is at the `fst`, and the collection to thread linearly is at `snd`.
No other changes. If there are any (not type-checked) documentation referring to the type signatures, they need to be fixed too.
See the discussion at #191 for more details.
> Consistent ordering of linear return values

- src/Control/Optics/Linear/Internal.hs
- src/Control/Optics/Linear/Lens.hs
The `withX` family of function is continuation-passing style. Probably
to avoid some allocations. The withLens function was not of this
shape, so I think it deserves another name. I like `reifyLens` for it,
so I used it.
I also added a quick implementation of a `withLens` function in terms
of `reifyLens`. Most certainly we can do a more direct implementation,
but I didn't take the time to think about it.
The getter/setter split of lenses doesn't really make sense for linear
lens. However, there is a presentation using an existential type which
does have such a shape. I decided to use it for `withLens`, by
symmetry with `withIso` and `withPrism`.
Depends on #219 #221 .
> withLens & reifyLens

- src/Control/Optics/Linear/Internal.hs
- src/Control/Optics/Linear/Lens.hs
- src/Control/Optics/Linear/Traversal.hs
It's more in line with the rest of linear-base. In an ideal word we
don't even need these function and over & traverse are multiplicity
polymorphic. But we are not there yet.
Depends on #219 #221 .
> Rename over'/traverseOf' -> overU/traverseOfU

- src/Data/Eq/Linear.hs
- src/Data/Monoid/Linear.hs
- src/Data/Ord/Linear.hs
- src/Data/Unrestricted/Linear.hs
Previously the `Ord` typeclass was implemented in terms of comparison operators (`<`, `>=` eg). And since a linear `compare` does not follow from them, it was implemented as:
```haskell
compare :: (Dupable a, Ur.Ord a) => a #-> a #-> Ordering
compare = Unsafe.toLinear2 Ur.compare
```
But, as established at #209, this approach is unsound. So that would force us to remove the `compare` function. However, that is unfortunate, because in the linear setting `compare` is strictly more powerful than the others. As another point, when implementing `Ord` instances for composite types, `compare` is a lot more useful since it saves us from implementing two separate, but very similar looking functions (`<` and `>`, for example).
So, the natural conclusion is to reverse the current state of affairs, …
> Implement Ord in terms of `compare`

- Setup.hs
- cabal.project
- linear-base.cabal
- src/Data/Array/Mutable/Linear.hs
- src/Data/V/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- src/Foreign/Marshal/Pure.hs
- src/Prelude/Linear.hs
- src/Streaming/Internal/Consume.hs
- src/Streaming/Internal/Many.hs
- src/Streaming/Internal/Process.hs
- src/Streaming/Internal/Produce.hs
- src/Streaming/Linear.hs
- src/System/IO/Resource.hs
- stack.yaml
- test/Doctest.hs
Closes #235.
This PR integrates `doctest` library to type-check and test the code examples in our Haddock's.
* It modifies our examples to look like REPL sessions instead of entire modules.
* There is an annoying `doctest` issue where we need to put an empty line after a multiline declaration, which doesn't look great. I'll file an upstream issue.
* As discussed on #232; `Streaming` modules are pretty big, so refactoring their examples would take a long time. So, this PR escapes their examples so they are not recognized by `doctest`.
* We're adding two new overrides for `syb` and `doctest`, both overrides have upstream PR's.
In order to try the tests, run `cabal test linear-base:doctests`, or an equivalent `stack` command. It is also a part of the longer `cabal test` command.
> Add doctest

- src/Control/Monad/Linear.hs
- src/Control/Monad/Linear/Internal.hs
It's a flipped `(<$>)`. Just like `(&)` is a flipped `($)`. It will be
useful for the pattern `u <&> \case …`.
> Add a (<&>) combinator

- src/Data/HashMap/Linear.hs
If anything, `alterF` is part of the optics story (it's a lens in the
style of #197). But it's also generally useful, if rarely so.
Also exposes `alter` (which has been mysteriously forgotten) and
`alterF` in the export list.
Depends on #147
> Add an alterF function to the HashMap module

- docs/DESIGN.md
- examples/Simple/TopSort.hs
- src/Data/Array/Mutable/Linear.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- src/Data/Vector/Mutable/Linear.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
- test/Test/Data/Mutable/Vector.hs
Closes #147 .
This PR updates the mutable collections API slightly to have consistency on order of parameters. The issue #147 has more reasoning behind the changes, but in short:
* The pure-looking names take the collection as the last parameter (`set`, `get`, `lookup`)
* Imperative-looking names take the collection as the first parameter (`read`, `write`)
For arrays and vectors, we both `set` and `get` methods alongside with the flipped versions as `read` and `write` (and their unsafe variants). However, unlifted arrays, maps and sets only have an entirely pure-looking interface. The only reason is that I did not find much value duplicating the entire API and making up new names for imperative-looking counterparts.
Let me know if you have another preference.
> Consistent parameter ordering of linear collections

- examples/Simple/TopSort.hs
- linear-base.cabal
- src/Data/HashMap/Mutable/Linear.hs
- src/Data/Set/Mutable/Linear.hs
- test/Test/Data/Mutable/HashMap.hs
Renamed to be consistent with `Data.Set.Mutable.Linear` and the layout of the tests in `/tests` and the overall naming convention used throughout.
> Renamed Data.HashMap.Linear to Data.HashMap.Mutable.Linear

- linear-base.cabal
- src/Data/Monoid/Linear.hs
- src/Data/Semigroup/Linear.hs
I put the `Data.Semigroup` stuff into a separate module. I had to allow orphan instances since `Endo` would be defined in the semigroup module. I hope that's not a dealbreaker.
> Created a Data.Semigroup.Linear module

- src/Unsafe/Linear.hs
Sometimes it's annoying to use `Unsafe.toLinear` or variants if a function is linear on some later argument and currying is tricky. This just makes that easier:
Before:
```haskell
toLinear2 :: (a -> b -> c) %1-> (a %1-> b %1-> c)
```
After:
```haskell
toLinear2 :: (a %p-> b %q-> c) %1-> (a %1-> b %1-> c)
```
> Made toLinear parametric in input functions multiplicity

- test/Test/Data/Mutable/Set.hs
Working towards closing #93 I've added tests for intersections and unions for sets.
[Remark: We should probably add tests for `empty` and maybe I should just do that in the PR but it looks obviously correct to me. (Saying this, I feel like I'm going to end up having to add it.)]
Issue #93 explains that the mutable data test suite is meant to provide properties which serve as axioms that define the behavior of how to interact with the data structure. That is, if all the properties hold, the behavior of the data structure is mathematically specified. For each accessor function `f` and each modifier or constructor `g` we have one axiom to specify the behavior of `f (g (...)) = ...`. See for instance [this](https://softwarefoundations.cis.upenn.edu/vfa-current/ADT.html) link. 
In this PR, …
> Testing set intersect and union

- src/Control/Optics/Linear/Internal.hs
Closes #229 
I ran `grep -nr ' as .$' .` in the base and got 
```bash
./src/Streaming/Prelude/Linear.hs:18:> import qualified Streaming.Prelude as S
./src/Streaming/Prelude/Linear.hs:28:> import qualified Pipes as P
./src/Streaming/Prelude/Linear.hs:29:> import qualified Pipes.Prelude as P
./src/Data/V/Linear.hs:31:-- >>> import qualified Data.V.Linear as V
./src/Data/Unrestricted/Linear.hs:91:import qualified Data.V.Linear as V
```
and the last two are OK because of the module name `Data.V.Linear` and the other ones are comments from the old streaming documentation.
> Renamed single-letter imports

- nixpkgs.nix
- shell.nix
Closes https://github.com/tweag/linear-base/issues/268.
I applied the fix mentioned at #268 to our fork of nixpkgs, rebased it to the current nixpkgs master (appearently it contains another fix for darwin builds), and pushed the branch to tweag's nixpkgs instead of my own. See the last two commits on https://github.com/tweag/nixpkgs/tree/78d9696f5d1524fcf2fd947f012ffc08fcba4dd1 for the nixpkgs changes.
I also added a parameter to `shell.nix` which allows passing `system` as a parameter (so I could test this change on a LInux machine with a darwin build machine.).
I tested that the `shell.nix` builds on both Linux and MacOS Mojave
> Fix builds on MacOS

- src/Control/Optics/Linear.hs
- src/Control/Optics/Linear/Traversal.hs
- src/System/IO/Resource.hs
Hi 👋! I was trying out this library and noticed that the examples refer to `Control.Monad.Linear` instead of `Control.Functor.Linear`. This PR fixes them.
> Rename module Control.Monad.Linear to Control.Functor.Linear in examples

- linear-base.cabal
- src/Data/V/Linear.hs
- src/Data/V/Linear/Internal/Instances.hs
We weren't able to create a `Instances` module for `Data.V.Linear` as we did for `Data.Functor.Linear` but this PR fixes that.
The issue: to be able to export a module, GHC requires that module to have something to export. 
Our other `Instances` modules exported something.
To get this to work I had `Data.V.Linear.Internal.Instances` re-export `Data.fmap` which is harmless since we have Data.Functor instances in it. [To be more precise, by "harmless", I mean for any use of `Data.V.Linear`, it will be indistinguishable from if the `Instances` module did not export anything.]
> Instances module for Data.V.Linear

- docs/USER_GUIDE.md
This addresses a comment in #278:
> It's completely unrelated, but do we have in our README, a documentation of our recommended qualifying conventions? That Data.Functor.Linear is typically qualified as Data?
> Import conventions for Data, Control

- src/Data/Array/Destination.hs
- src/Data/Array/Polarized.hs
- src/Data/Array/Polarized/Push.hs
This PR flushes out the design laid out in the `better-push-array` branch. [In an effort to avoid plagiarism: note that all of these are @aspiwack's ideas.] We represent push arrays with this clever little rank-2 thing:
```haskell
data Array a where
Array :: (forall m. Monoid m => (a -> m) -> m) %1-> Array a
```
that takes a polymorphic conversion to a monoid for some element, and creates a monoid. This way it represents the monoidal concatenation of a certain natural (including zero) number of `a`s, in some unknown order.
We instantiate this with a function that takes an `a` and makes it an `ArrayWriter a`:
```haskell
data ArrayWriter a where
ArrayWriter :: (DArray a %1-> ()) %1-> !Int -> ArrayWriter a
```
which holds the ingredients needed to write some number of elements, without …
> More generic push arrays 1/2

- src/Data/Array/Polarized/Push.hs
This PR adds to push arrays:
- folds and unzip and closes #80 
- more flexible construction and closes #62 
Depends on #287.
- I don't fully understand the role of linear types here. Is it just to have the linear monoid so that the type necessarily writes each element once (and that in the allocation, we use destination arrays). Can we come up with a concise statement of how we apply linear types?
- Aren't we still missing the "use each index only once" property of pull arrays?
> Push arrays/fold

- src/Data/Array/Destination.hs
Closes #289. The only note is that I couldn't remove all `Unsafe.toLinear` calls since `fill` uses the filling value linearly and that is written to a mutable vector using `MVector.write`.
> Changed destination type to have less unsafe linear casts

- cabal.project
- linear-base.cabal
- nixpkgs.nix
- shell-stack.nix
- shell.nix
- stack.yaml
I did some housekeeping before the release.
* I switched using `ghc901` instead of `ghcHEAD`, and updated our `nixpkgs` fork to use the released binaries.
* I removed `quickcheck` and `syb` overrides since the required updates are merged & released.
* I increased the base lower bound to the one released with GHC 9, so the install plan will fail with olde GHC's.
* I updated the stackage resolver to get up-to-date packages (includes the released fixes I mentioned above).
However, I couldn't enable doctests. I think `cabal-install` coming from our nix expressions need to be updated before that.
(CI might take a while to complete since it has to compile a new GHC.)
> Update dependencies and remove obsolete overrides

- src/Data/List/Linear.hs
They only appear when linear-base with ghc HEAD (`ab5fd982`, slightly
newer than GHC 9.0.1 release). Likely the recent pattern exhaustiveness
checking are relevant, but I don't know why the released version not throws
these errors.
Anyhow, unfortunately they're only exhaustive because of the implementation
rather than the types, so I added other cases as bottoms.
(Making `scanr` return `NonEmpty` would solve one of the problems, but I do
not think it's worth diverging the API from `Data.List` and also we don't have
`Data.List.NonEmpty.Linear`)
> Remove some incomplete pattern matches

- nixpkgs.nix
After nixpkgs [commit `0b626654`][1] is merged there is no point having
our own fork. This commit updates our nixpkgs fork to latest master
(as of 2021-02-15). This has the added advantage that now we can use
the default NixOS binary cache.
[1]: https://github.com/NixOS/nixpkgs/commit/0b626654adb3c24067846012c58651587e551df1
> Start using upstream nixpkgs

- src/Control/Optics/Linear/Internal.hs
- src/Data/Profunctor/Linear.hs
I'm trying to add support for generating linear traversals to my one-liner package, and noticed this instance is missing. I could use the `LinearArrow` instance instead, but having this instance makes things a bit cleaner.
> Add FUN 'One Profunctor instance

- src/Data/Monoid/Linear/Internal/Monoid.hs
I need the `Monoid ()` instance for deriving `Consumable` instances with a linear `foldMap`.
> Add missing Monoid instances

- .github/workflows/ci.yaml
Now that we don't need to build GHC ourselves for the sake of
linear-base to work, we don't need to lock a super beefy runner for 1h
from time to time.
On the other hand, the buildkite runner didn't run ci for
contributions outside of Tweag. Having a Github-action based ci will
be better for contributors.
I'll remove the Buildkite ci in a separate PR.
> Add a Github action ci

- examples/Test/Foreign.hs
- src/Data/Array/Destination/Internal.hs
- src/Prelude/Linear/Internal.hs
- src/Streaming/Internal/Produce.hs
- src/System/IO/Resource.hs
- src/System/IO/Resource/Internal.hs
- test/Test/Data/Mutable/HashMap.hs
What I've done is take the prelude functions that we use all the time
and polymorphise the higher-order arrows.
I left the first order arrow to multiplicity 1 whenever possible
because:
- We can cast them to any multiplicity by a simple 𝜂-expansion
- Any multiplicity involving multiplicity multiplication will hit the
limitations of the type checker currently (it doesn't know that
multiplication is associative, typically), so I really wanted a
single multiplicity variable per type.
This does leave composition fully linear, unfortunately, because there
are two (independent) higher-order arrow, and there is no most general
choice of one to polymorphise.
It didn't work last time I tried, but @monoidal made a [cleverly short
patch](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4632) to …
> Polymorphise the type of some functions

- cabal.project
- nixpkgs.nix
- stack.yaml
Our dependencies has catched up to GHC 9, and we do need any of our forks now.
This PR updates stackage resolver and removes the overrides on cabal.project and stack.yaml.
> Update dependencies and remove overrides

- linear-base.cabal
- src/Data/Array/Mutable/Linear/Internal.hs
Closes #214.
Turns out there is [a recent addition](https://hackage.haskell.org/package/vector-0.12.3.0/docs/Data-Vector.html#v:fromArray) to `vector` library since version `0.12.2.0`:
```
fromArray :: Data.Primitive.Array a -> Vector a
```
This is very close to what we were looking for, so this PR uses that to simplify our `Data.Array.Mutable.Linear.freeze` function.
I also added a lower bound to `vector` package to ensure that we don't get an old one.
> Use safer Vector.fromArray

- src/Prelude/Linear/Internal.hs
This simple change both looks nicer, and also speeds up
one of my (yet unpublished) local benchmarks considerably.
I think calling `toLinear` is very costly, since the `coerce`
does not inline and the parameter to it ends up being an allocation.
Surely my terminology here is not quite right, and I would love to
know more about how the `coerce` is handled on the simplifier and
core prep, so please do correct me.
> Simplify 'seq' for performance

- src/Unsafe/Linear.hs
Previously, the linear `Unsafe.coerce` was implemented using two `unsafeCoerce`'s, one to get a function `a -> b`, and another one to cast that function to be a linear one.
After the [unsafe equality proofs change][1], we have a `unsafeEqualityProof` function to cast two types to be the same without looking at the value, so we can linearly return it, removing the need for the outer `unsafeCoerce`.
This removes one allocation from the generated STG code for `Data.Array.Unlifted.get`, improving the performance slightly.
[1]: https://gitlab.haskell.org/ghc/ghc/-/commit/74ad75e87317196c600dfabc61aee1b87d95c214
> Remove a 'unsafeCoerce' from 'Unsafe.coerce'

- bench/Data/Mutable/Array.hs
- bench/Main.hs
- linear-base.cabal
Slightly more details on issue #328.
I only spent time on `reads` benchmark, which creates an array
and iterates on it. On a recent GHC HEAD (`378c0bba7d`), here're
the current results:
```
$ cabal bench --benchmark-options 'arrays/reads'
...
benchmarked arrays/reads/Data.Array.Mutable.Linear
time                 191.7 ms   (185.3 ms .. 195.9 ms)
0.999 R²   (0.997 R² .. 1.000 R²)
mean                 213.9 ms   (206.2 ms .. 226.2 ms)
std dev              16.61 ms   (9.796 ms .. 25.32 ms)
variance introduced by outliers: 19% (moderately inflated)
benchmarked arrays/reads/Data.Vector
time                 58.77 ms   (58.64 ms .. 58.88 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 67.59 ms   (64.36 ms .. 75.56 ms)
std dev              8.991 ms   (3.925 ms .. 14.61 ms)
variance …
```
> Add linear mutable array benchmarks

- Setup.hs
This allows projects to depend on linear-types without depending on cabal-doctest
> No cabal-doctest in Setup.hs

- README.md
Closes #333.
`linear-base` is now on Stackage, starting with `nightly-2021-06-30`. So this PR adds a badge mentioning this to README.md.
I also added a badge for the Hackage package, just for completeness. It doesn't give much information but I find those handy to jump into the Hackage/Stackage pages.
> Add Hackage and Stackage badges

- src/Data/HashMap/Mutable/Linear/Internal.hs
Just some minor optimisations for our HashMap implementation. It contains
a few unrelated small changes, so reviewing each individual commit might
be easier.
When I compare this against `Data.HashMap.Strict`, the results change based
on the input (likely based on the hash distribution of the key). I need to investigate
this more. Just as reference, here're the functions I am comparing (`Key` is just a
newtype wrapper around `Int`):
```
linear :: [Key] -> HashMap.Linear.HashMap Key () %1-> ()
linear inp hm = go inp hm `Linear.lseq` ()
where
go :: [Key] -> HashMap.Linear.HashMap Key () %1-> HashMap.Linear.HashMap Key ()
go [] h = h
go (x:xs) h = go xs Linear.$! HashMap.Linear.insert x () h
dataHashMap :: [Key] -> Data.HashMap.Strict.HashMap Key () -> ()
dataHashMap inp hm = go inp hm `seq` …
```
> Various HashMap optimisations

- bench/Data/Mutable/HashMap.hs
- bench/Main.hs
- linear-base.cabal
This PR adds a benchmark for `Data.HashMap.Mutable.Linear` which inserts a bunch of keys in random order. Here're some details of the benchmark:
* The keys are unique, so there are no updates.
* The hashmap is initialized to be twice as big as the input size to avoid resizes.
* The keys are newtype wrappers around `Int`'s for which the `hash` value is salted with a large number.
Here's the result of the benchmark on GHC HEAD (`378c0bba7d`):
```
$ cabal bench --benchmark-options 'hashmaps/microbenchmarks/insertHeavy'
...
Benchmark mutable-data: RUNNING...
benchmarked hashmaps/microbenchmarks/insertHeavy/Data.HashMap.Mutable.Linear
time                 45.20 ms   (44.88 ms .. 45.62 ms)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 44.56 ms   (44.11 ms .. 44.90 ms)
std dev …
```
> Add hashmaps/microbenchmarks/insertHeavy benchmark

- cabal.project
For some reason [we started getting](https://github.com/tweag/linear-base/runs/3372126892):
```
cabal: Cannot test the package linear-base-0.1.1 because none of the
components are available to build: the test suite 'test' and the test suite
'examples' are not available because the solver did not find a plan that
included the test suites. Force the solver to enable this for all packages by
adding the line 'tests: True' to the 'cabal.project.local' file.
```
On the CI, even on our branches without any build system related changes. It's not clear to my why is this happening, but the only mutable thing I can think of is the Hackage index, so probably a version of a package is released and that is confusing cabal. 
Anyhow, adding `tests: true` to `cabal.project` as suggested seems to fix the …
> Force resolving test dependencies on cabal

- .github/workflows/ci.yaml
With just `push`, CI doesn't run on third party PRs.
> Run CI on PRs

- src/Unsafe/Linear.hs
* Make `toLinear`, etc., explicitly coerce only *multiplicities*,
rather than whole arrow types. This is just a cleanup; it shouldn't
have any practical impact.
* Add `toLinearN` and `toLinearL` to generalize `toLinear`, `toLinear2`, and `toLinear3`.
> Add toLinearN; narrow the coercion scope

- src/Data/V/Linear.hs
- src/Data/V/Linear/Internal.hs
`V n a` represents vector having `n` elements of type `a`. Such a vector can be built using the `make` function, taking `n` linear arguments of type `a`, and returning a `V n a`.
At the moment, `make` uses a lot of type-level machinery around `Nat`s, and is implemented in a way such that it cannot be inlined; even if `n` is compile-time known.
With https://github.com/tweag/linear-base/pull/360 (now merged), the `Data.V.Linear` module has been overhauled, and the `elim` function has been rewritten to be inlinable.
The aim of this PR is to provide an efficient `make` implementation using typeclasses so as to make it inlinable when `n` is known at compile-time. It also adds more symmetry between `make` and `elim`, and allows us to get rid of a lot of internal helper functions.
> Improve `make`/`Make` implementation for `Data.V.Linear`

- format.sh
- linear-base.cabal
- test/Test/Data/Mutable/Vector.hs
This helps, in particular, when developping with ghcid, which
otherwise doesn't raise warnings.
I've had to deactivate `cabal` format in the formatting script due to
the fact that it inlines `common` stanzas, which I'm using to ensure
consistent warning settings in every target. See
[haskell/cabal#5734](https://github.com/haskell/cabal/issues/5734).
---
I've written this while I was trying to do something smart with the
`Elim` and `Make` type classes. It didn't work. So there won't be a
followup PR, but this one is worth it on its own, I think.
> Add warnings to the cabal file

- src/Data/Replicator/Linear/Internal.hs
- src/Data/V/Linear/Internal.hs
- test/Test/Data/Replicator.hs
- test/Test/Data/V.hs
`Replicator.elim` and `V.elim` are currently not inlined if they are not fully applied (as we found out when writing inspection tests for this method). For example, in the following case, `elim` doesn't get inlined:
```haskell
elim3 :: (a %1 -> a %1 -> a %1 -> [a]) %1 -> V 3 a %1 -> [a]
elim3 = V.elim
```
This PR renames `elim` to `elim'` and add a `elim` wrapper ensuring that `elim'` can always get inlined.
(I also move `make` into the `Make` class in this PR, for consistency with `Elim`)
Closes #369 .
> Force eta-expansion of `{Replicator,V}.elim`

- docs/DESIGN.md
- docs/USER_GUIDE.md
- examples/Simple/FileIO.hs
- linear-base.cabal
- src/Control/Functor/Linear/Internal/Class.hs
- src/Control/Functor/Linear/Internal/Reader.hs
- src/Control/Functor/Linear/Internal/State.hs
- src/Data/Arity/Linear/Internal.hs
- src/Data/Functor/Linear/Internal/Functor.hs
- src/Data/Replicator/Linear/Internal.hs
- src/Data/Replicator/Linear/Internal/ReplicationStream.hs
- src/Data/Unrestricted/Linear.hs
- src/Data/Unrestricted/Linear/Internal/Consumable.hs
- src/Data/Unrestricted/Linear/Internal/Dupable.hs
- src/Data/Unrestricted/Linear/Internal/Instances.hs
- src/Data/Unrestricted/Linear/Internal/Movable.hs
- src/Data/Unrestricted/Linear/Internal/Ur.hs
- src/Data/Unrestricted/Linear/Internal/UrT.hs
- src/Data/V/Linear.hs
- src/Data/V/Linear/Internal.hs
- src/Streaming/Linear.hs
- src/Streaming/Linear/Internal/Consume.hs
- src/Streaming/Linear/Internal/Interop.hs
- src/Streaming/Linear/Internal/Many.hs
- src/Streaming/Linear/Internal/Process.hs
- src/Streaming/Linear/Internal/Produce.hs
- src/Streaming/Linear/Internal/Type.hs
- src/Streaming/Prelude/Linear.hs
- src/System/IO/Resource/Linear.hs
- src/System/IO/Resource/Linear/Internal.hs
Before 1.0 release, I think that we should ensure that our naming conventions are respected for both internal and public modules.
In this PR, I renamed:
+ System.IO.Resource -> System.IO.Resource.Linear
+ Streaming.Internal -> System.Linear.Internal
+ Data.Unrestricted.Internal -> Data.Unrestricted.Linear.Internal
+ Data.Arity.Linear.Internal.Arity -> Data.Arity.Linear.Internal
The `Control.Optics` directory structure seemed a bit odd to me (but I haven't changed it yet), because it contains modules not ending with either `.Linear` or `.Linear.Internal.xxx` as this is the case in every other namespace. Should we rename something for this one?
Closes #373 . Closes #380 .
> Improve consistency of module naming

- src/Control/Functor/Linear.hs
- src/Control/Functor/Linear/Internal/Class.hs
Apply decision of PR #356 : we should have a `void :: (Functor f, Consumable a) =>  f a %1 -> f ()` function not only for `Data.Functor.Linear.Functor` but for `Control.Functor.Linear.Functor` as well.
Closes #356.
> Add `void` function to consume `Control.Functor.Linear.Functor` inner value

- examples/Simple/FileIO.hs
- examples/Simple/Pure.hs
- src/Control/Functor/Linear/Internal/Class.hs
- src/Control/Optics/Linear/Internal.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/Bool/Linear.hs
- src/Data/Functor/Linear/Internal/Applicative.hs
- src/Data/Functor/Linear/Internal/Functor.hs
- src/Data/List/Linear.hs
- src/Data/Monoid/Linear/Internal/Semigroup.hs
- src/Data/Num/Linear.hs
- src/Data/Ord/Linear/Internal/Eq.hs
- src/Data/Ord/Linear/Internal/Ord.hs
- src/Data/Profunctor/Linear.hs
- src/Data/Replicator/Linear/Internal.hs
- src/Data/Replicator/Linear/Internal/ReplicationStream.hs
- src/Data/Unrestricted/Linear/Internal/Consumable.hs
- src/Data/V/Linear/Internal.hs
- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal.hs
- src/Streaming/Linear/Internal/Consume.hs
- src/Streaming/Linear/Internal/Type.hs
Precedence levels are chosen to be same as in base.
The only exception is `compare`, for which I chose `infix 4` like every other `a -> b -> Bool` operator (`elem`, `<`, `<=`, `==`...).
Closes #374 .
> Add fixity declaration for every operator of `linear-base`

- src/Control/Functor/Linear/Internal/Kan.hs
- src/Data/Functor/Linear/Internal/Traversable/Generic.hs
Just small docstring fixes.
@sjoerdvisscher, you pioneered the use of `Yoneda` and `Curried` for
fusion. Could you write the missing bit of documentation?
> Some documentation on genericTraverse and friends

- shell.nix
- src/Control/Functor/Linear/Internal/Kan.hs
- src/Data/Arity/Linear/Internal.hs
- src/Data/Replicator/Linear/Internal.hs
- src/Data/Unrestricted/Linear/Internal/Dupable.hs
- test/Test/Data/V.hs
I rely on more type families (I resurrected the `FunN` type family,
for instance) and additional type classes in order to give robust
hints to the type checker to infer some of the arguments based on the
others in multiple possible ways.
The previous version was abusing functional dependencies to that
effect. The problem is that it almost certainly depended on bugs. Plus
some behaviour changed in 9.2 making the recursive instance not
typecheck anymore.
The actual (staging) recursion now uses (type-level) Peano integers,
this way we can get rid of the `OVERLAPPABLE` instances altogether,
and avoid the sort of fragile behaviour that caused the failure in
9.2.
The 'elim' function itself has more type arguments, so I took it out
of the type class. A collection of type families and type …
> A more robust implementation of Replicator.elim

- examples/Generic/Traverse.hs
- src/Control/Optics/Linear/Internal.hs
- src/Data/Array/Polarized.hs
- src/Data/Functor/Linear/Internal/Applicative.hs
- src/Data/List/Linear.hs
- src/Data/Monoid/Linear/Internal/Monoid.hs
- src/Data/Monoid/Linear/Internal/Semigroup.hs
- src/Data/Num/Linear.hs
- src/Data/Unrestricted/Linear/Internal/Instances.hs
- src/System/IO/Linear.hs
- src/System/IO/Resource/Linear/Internal.hs
+ Break relationship between `Data.Monoid.Linear.{Semigroup,Monoid}` and their
non-linear counterparts (see https://github.com/tweag/linear-base/issues/379)
+ Add as many instances as possible for these classes (to replicate what is done
in `base`
Closes #379. Closes #372.
> `Semigroup` and `Monoid` overhaul

- linear-base.cabal
- src/Data/Arity/Linear.hs
- src/Data/Arity/Linear/Internal.hs
- src/Data/Replicator/Linear/Internal.hs
- src/Data/V/Linear.hs
- src/Data/V/Linear/Internal.hs
+ Rework `V.{make,elim}` to use the same type-level machinery as
the new `Replicator.elim` implementation introduced by @aspiwack in https://github.com/tweag/linear-base/pull/390
+ Improve documentation of `V.{make,elim}`, `Replicator.elim` and `Arity` module
+ Expose the type-level helpers from the internal `Arity` module as `Data.Arity.Linear`
> Finish robustness improvements on `make`/`elim`

- src/Prelude/Linear.hs
- src/Prelude/Linear/Internal.hs
Closes #354 . The linked issue gives the motivations behind this removal.
> Remove `Prelude.Linear.asTypeOf`

- .github/workflows/ci.yaml
Cabal do not pick the same Hedgehog version as stack, so we get deprecation warnings (treated as errors) in the cabal CI.
> Move CI tests from cabal job to stack job

- CHANGELOG.md
PRs submitted before 2022/02/25 16:00:00 have been taken into account at this point.
The file `CHANGELOG-ENTRIES--delete-before-merge.md` is the output I got from the [github-changelog-generator](https://github.com/github-changelog-generator/github-changelog-generator) tool. I then looked at each PR, improved its title/description, and added it to the right group in `CHANGELOG.md`. 
Closes #377 .
> Prepare Changelog for v0.2.0

- linear-base.cabal
When I tried to upload v0.2 to hackage with `stack upload .`, I got:
```
Getting file list for /home/tbagrel/tweag/linear-base/
linear-base> List of package sources written to file
linear-base> '/run/user/1000/stack-sdist-3581103229e842f1/source-files-list'
Building sdist tarball for /home/tbagrel/tweag/linear-base/
Checking package 'linear-base' for common mistakes
Package check reported the following warnings:
The 'description' field should be longer than the 'synopsis' field. It's useful to provide an informative 'description' to allow Haskell programmers who have never heard about your package to understand the purpose of your package. The 'description' field content is typically shown by tooling (e.g. 'cabal info', Haddock, Hackage) below the 'synopsis' which serves as a headline. …
```
> Fix `linear-base.cabal` to allow upload on Hackage

- CHANGELOG.md
- README.md
- docs/USER_GUIDE.md
Thanks to this PR, the README displayed on [Hackage](https://hackage.haskell.org/package/linear-base) will have valid links.
> Change relative links for absolute ones in the README

- src/Data/Monoid/Linear/Internal/Monoid.hs
This only needs a `Semigroup` constraint; with a `Monoid` constraint it's almost useless!
> Weaken constraint on Monoid (Maybe a) instance

- examples/Generic/Traverse.hs
- examples/Test/Foreign.hs
- examples/Test/Quicksort.hs
- linear-base.cabal
- stack.yaml
- stack.yaml.lock
- test/Test/Data/Destination.hs
- test/Test/Data/Mutable/Array.hs
- test/Test/Data/Mutable/HashMap.hs
- test/Test/Data/Mutable/Set.hs
- test/Test/Data/Mutable/Vector.hs
- test/Test/Data/Polarized.hs
The `testProperty` function has been deprecated in the current 1.2
version. See https://github.com/qfpl/tasty-hedgehog/pull/42 for the
reason.
The `testProperty` function is replaced by `testPropertyNamed` which
requires one extra argument (the name of the test function as a
string).
There were a test for which the property didn't have a name, so I had
to name it. We also need `-XOverloadedString` in every module (some
already have it).
---
This is extracted from #414 , which was supposed to be a 5min fix and turned
out to spiral out of control. I realised it was possible to turn it back into a 5min
fix: add the more recent version of tasty-hedgehog to the `extra-deps`.
> Don't use deprecated `testProperty` from tasty-hedgehog

- src/Data/Array/Mutable/Linear/Internal.hs
There’s a missing quote here, which is preventing the reference from being hyperlinked (e.g. on Hackage).
> Fix haddock hyperlink reference (minor typo)

- bench/Data/Mutable/HashMap.hs
- nix/sources.json
- shell.nix
- src/Control/Functor/Linear/Internal/Class.hs
- src/Data/Functor/Linear/Internal/Applicative.hs
- stack.yaml
- stack.yaml.lock
Part of #389.
---
This PR originally fixed the tasty-hedgehog deprecation warning. But because it turned out to that GHC 9.2 is having problem with our PR, I extracted this bit in #415.
I'll rebase on master as soon as #415 is merged to clear up the tasty-hedgehog bits.
---
Edit: I wanted to only make a draft PR, but I misclicked. I don't think that
I can convert it back. I don't know how anyway. I don't want to merge quite
yet, as there is a bug related to `stack ghci` which causes an anomaly in GHC:
```
$ stack ghci
Stack has not been tested with GHC versions above 9.0, and using 9.2.2, this may fail
Stack has not been tested with Cabal versions above 3.4, but version 3.6.3.0 was found, this may fail
Configuring GHCi with the following packages: linear-base
GHCi, version 9.2.2: …
```
> Upgrade GHC to 9.2

- src/System/IO/Resource/Linear/Internal.hs
Hope it’s ok to make such a minor PR! Saw the typo and figured it might as well be fixed.
> Fix typo in comment: resrouce -> resource

- CHANGELOG.md
- src/System/IO/Resource/Linear.hs
- src/System/IO/Resource/Linear/Internal.hs
Add `System.IO.Resource.Linear.{openBinaryFile,hSeek,SeekMode(..),hTell}`.
Haddocks are in anticipation of a near 0.2.1 release; happy to change/remove the `@since` annotations if they're likely to be wrong.
Related: #424.
> Add some Handle operations to RIO

- nix/sources.json
- shell.nix
- src/Data/Functor/Linear/Internal/Applicative.hs
- src/Streaming/Linear/Internal/Many.hs
- src/Streaming/Linear/Internal/Produce.hs
- src/System/IO/Resource/Linear.hs
- stack.yaml
- stack.yaml.lock
This PR updates `nix-shell` to enable building with either GHC 9.2.4 or 9.4.1. This required updating the stackage resolver to a 9.2.4-compatible one, which then also resulted in some formatting changes. 
The actual work of updating linear-base to build in 9.4.1 will come in a separate PR, so as not to muddle the diffs too much.
> Update nix-shell to enable building with GHC 9.4.1

- src/System/IO/Linear.hs
There's no obvious reason to use an unsafe coercion here. We just need to eta expand for linearity.
> Implement toSystemIO safely

- bench/Data/Mutable/Array.hs
- bench/Data/Mutable/HashMap.hs
- bench/Main.hs
- linear-base.cabal
This commit replaces the `gauge` benchmark framework with `tasty-bench` for the `linear-base:bench` target. The API is the same in both tools, so the change is mostly transparent.
> Moving from gauge to tasty-bench

- src/Data/List/Linear.hs
Deprecate `Data.List.Linear.{cycle,repeat,iterate}`. Infinite results cannot be consumed linearly, so they are not really useful in a linear context. They could be consumed by a program that exits via an exception, but I don't think that's something that should really be supported.
Begins to address #453
> Deprecate cycle, repeat, and iterate

- src/Control/Functor/Linear/Internal/Class.hs
- src/Data/Functor/Linear/Internal/Functor.hs
As reported in #459, `linear-base` accidentally lacked `Functor` instances for a linear arrow.
This PR adds them.
> Adds `Functor` instances for a linear arrow

- src/Data/Monoid/Linear/Internal/Monoid.hs
- src/Data/Monoid/Linear/Internal/Semigroup.hs
This PR adds linear `Semigroup` and `Monoid` instances for `Ur`, which turns unrestricted ones into linear ones.
This instance is particuarly useful when one extract unrestricted monoidal value out of linear values; e.g. `foldMap` of Pull and/or Push Arrays.
I used them to [test my custom vector-generic `fromVector` for pull arrays without allocating vector](https://github.com/konn/linear-array-extra/blob/main/test/Data/Array/Polarized/Pull/ExtraSpec.hs#L50) ([corresponding instance definition](https://github.com/konn/linear-array-extra/blob/c6c89ac424620a2ebde41a52dce8241c2799e65f/test/Linear/Array/Extra/TestUtils.hs#L249-L253))
> Implements `Semigroup` / `Monoid` instances for `Ur`

- linear-base.cabal
- src/Data/Num/Linear.hs
- src/Data/Unrestricted/Linear/Internal/Instances.hs
This PR fixes two (related) issues (#403 and #466):
- Movable (and derived `Consumable`/`Dupable`) instances are added for `Integer` and `Natural`. This is safe since these types are represented as strict sum types whose elements are unlifed unboxed primitives so there is no way laziness might break linearity in there. (See also the [last part of the discussion in #403](https://github.com/tweag/linear-base/issues/403#issuecomment-1706679338))
- Instances for the typeclasses in `Data.Num.linear` (`Additive`/`AddIdentity`/`AdditiveGroup`/`Multiplicative`/`MultIdentity`/`Semiring`/`Ring`/`Num`) for the general-purpose number types that exist in the Prelude/`base` which were still missing them:
- `Word`
- `Float`
- `Integer`
- `Natural`
- `Word8`/`Word16`/`Word32`/`Word64`
- …
> Adds missing Data.Num.Linear.* instances for Word, Integer, Natural, Float, Word8/16/32/64 Int8/16/32/64

- bench/Data/Mutable/HashMap.hs
- docs/USER_GUIDE.md
- examples/Simple/TopSort.hs
- src/Control/Optics/Linear/Internal.hs
- src/Control/Optics/Linear/Prism.hs
- src/Data/Array/Mutable/Linear/Internal.hs
- src/Data/Functor/Linear/Internal/Traversable.hs
- src/Data/HashMap/Mutable/Linear/Internal.hs
- src/Data/List/Linear.hs
- src/Data/Monoid/Linear/Internal/Semigroup.hs
- src/Data/Ord/Linear/Internal/Ord.hs
- src/Data/Replicator/Linear/Internal.hs
- src/Data/Replicator/Linear/Internal/ReplicationStream.hs
- src/Data/Unrestricted/Linear/Internal/Instances.hs
- src/Data/Unrestricted/Linear/Internal/Movable.hs
- src/Data/V/Linear/Internal.hs
- src/Data/Vector/Mutable/Linear/Internal.hs
- src/Streaming/Linear.hs
- src/Streaming/Linear/Internal/Consume.hs
- src/Streaming/Linear/Internal/Many.hs
- src/Streaming/Linear/Internal/Process.hs
- src/Streaming/Linear/Internal/Produce.hs
- test/Test/Data/Mutable/Vector.hs
- test/Test/Data/Replicator.hs
- test/Test/Data/V.hs
Since #442 we require GHC >= 9.2. We can drop the workaround, which was needed for 9.0 only.
Tested by building with 9.2 and 9.6.
> Remove the ... & \case -> ... workaround

- CONTRIBUTING.md
- README.md
(And remove the long obsolete Buildkite badge)
> Add invite link to Discord

- src/Data/Array/Mutable/Linear/Internal.hs
- src/Data/Array/Mutable/Unlifted/Linear.hs
- src/Data/HashMap/Mutable/Linear/Internal.hs
- src/Data/Set/Mutable/Linear/Internal.hs
- src/Data/Vector/Mutable/Linear/Internal.hs
- src/Foreign/Marshal/Pure/Internal.hs
Functions of the form
```haskell
f :: (A %1 -> Ur b) %1 -> Ur b
```
are now of the form
```haskell
f :: Movable b => (A %1 -> b) %1 -> b
```
The new type is strictly more general. Technically this seems to involve some extra allocations here and there. I expect it to be negligible (we don't want to call too many scoped functions anyway).
The extra allocation is interesting, in that it's not always strictly necessary: when returning an `Int`, I don't need to produce an `Ur Int` to make sure that I've actually forced everything, just returning the forced `Int` would do the trick. Yet we use an `Ur Int` to communicate that we've indeed done the job (in some cases the optimiser can actually remove the extra allocation, but not in every case as far as I can tell). Maybe there are cheaper way …
> In scope-passing style: use a `Movable b` instead of `Ur b`

- .github/workflows/ci.yaml
- cabal.project
- linear-base.cabal
- nix/cabal-docspec.nix
- nix/sources.json
- nix/sources.nix
- shell.nix
- src/Data/Unrestricted/Linear/Internal/Instances.hs
- src/Data/V/Linear/Internal.hs
- stack.yaml
- stack.yaml.lock
This pull request changes the default version of GHC to be the one used by the latest stackage LTS available at the moment.
> Bump nixpkgs, bump GHC to 9.6.6 and stackage to LTS 22.34

- .github/workflows/ci.yaml
- bench/Data/Mutable/Quicksort.hs
- bench/Main.hs
- cabal.project
- examples/Simple/Quicksort.hs
- linear-base.cabal
- test-examples/Main.hs
- test-examples/Test/Simple/Quicksort.hs
This PR adds a proper benchmark for quicksort, across 3 methods and 3 list sizes, as encouraged by [this thread](https://discourse.haskell.org/t/linear-haskell-quicksort-performance/10280/9). It also runs and exports benchmark results to an artifact for each GHC version in the CI matrix so it will be easier to check for potential performance regression in the future. The PR builds upon https://github.com/tweag/linear-base/pull/479 and https://github.com/tweag/linear-base/pull/480
Here are the results I got :
**GHC 9.4.8**
**/!\\** *Done locally on my computer, so ordering between methods is valid, but absolute times should not be compared to other results below* **/!\\**
```
quicksort
size 1000
linArrayQuicksort:                                                         OK
773  μs ±  65 μs …
```
> Add Quicksort benchmark and export benchmark results as an artifact

- .github/workflows/ci.yaml
- linear-base.cabal
- src/Data/List/Linear.hs
- test/Main.hs
- test/Test/Data/List.hs
> do not drop extra elements in Data.List.Linear drop and take
