src/System/IO/Resource.hs
Release of the resources is done under the bracket so it
prevents from async exception, unless operations are interruptible.
But in case of interruptible exceptions some resources may not
be released.
This commits fixes the issue by releasing resources even if
asynchronous exception arrives during resource.
=> Fix exceptional case in release.

.circleci/config.yml, src/Prelude/Linear.hs, src/System/IO/Linear.hs, src/System/IO/Resource.hs
Just building with `--pedantic` for the moment.
=> Set up a CI

.circleci/config.yml, examples/Spec.hs, linear-base.cabal, src/System/IO/Resource.hs, stack.yaml
=> Update docker image to 0.1.9

.dir-locals.el, stack.yaml
Miscellaneous fixes. Will merge when green.
=> Make my life easier

.circleci/config.yml, examples/Spec.hs
=> Fix example tests

src/System/IO/Resource.hs
This shouldn't have type checked, though.
=> Fix: confusion between the non-linear and the linear $

.circleci/config.yml, examples/Foreign/List.hs, examples/Spec.hs, src/Control/Monad/Linear.hs, src/Control/Monad/Linear/Builder.hs, src/Foreign/Marshal/Pure.hs, src/Prelude/Linear.hs, src/System/IO/Linear.hs, src/System/IO/Resource.hs, src/Unsafe/Linear.hs, stack.yaml
Just for testing and notification. No need for review.
=> Bump to linear-types:1.0.0

src/Prelude/Linear.hs
Unrestricted forms a Data Applicative, but not a Control Applicative.
=> Add Applicative instance for Unrestricted

src/Control/Monad/Linear.hs, src/System/IO/Linear.hs, src/System/IO/Resource.hs
Add superclasses Data.Functor => Control.Functor and similarly for Applicative; along with default definitions to conveniently define such instances.
=> Superclass relations

src/Prelude/Linear.hs
Add basic combinators to deconstruct the `Either` and `Maybe` types linearly
=> Allow linear deconstruction of Either and Maybe

src/Control/Optics/Linear/Internal.hs, src/Data/Profunctor/Linear.hs, src/Prelude/Linear.hs
Adjust `Wandering` to use the linear Traversable class
=> Make wandering use Data.Traversable

src/Control/Optics/Linear/Internal.hs
Add optic composition combinator
=> Optic composition operator

examples/Foreign/Heap.hs, examples/Spec.hs, linear-base.cabal
=> restore heap example (#18)

linear-base.cabal, src/Data/Functor/Linear/Internal.hs, src/Data/Monoid/Linear.hs, src/Data/Unrestricted/Linear.hs, src/Data/Vector/Linear.hs, src/Prelude/Linear.hs
Resolving issues from #51 and #46
=> Linear semigroups v3

examples/Foreign/Heap.hs, examples/Spec.hs, linear-base.cabal, src/Data/Array/Destination.hs, src/Data/Array/Polarized.hs, src/Data/Array/Polarized/Pull/Internal.hs, src/Data/Array/Polarized/Push.hs
A collection of tests for linear arrays
=> Tests for destination and polarized arrays

.circleci/config.yml, stack.yaml
=> Update CI to use a more recent linear-ghc build

examples/Spec.hs, src/Data/Array/Destination.hs, src/Data/Array/Polarized.hs
=> Avoid allocating in DArray.fromFunction (#59)

src/Data/Array/Destination.hs, src/Data/Array/Polarized.hs, src/Data/Array/Polarized/Pull.hs, src/Data/Array/Polarized/Pull/Internal.hs, src/Data/Array/Polarized/Push.hs, src/Data/Monoid/Linear.hs
Add some documentation for destination arrays and polarized arrays.
Also remove some unnecessary pragmas and fix a loop in linear monoids.
=> Some basic documentation for arrays

examples/Spec.hs, linear-base.cabal, src/Control/Optics/Linear/Internal.hs, src/Data/Num/Linear.hs, src/Data/Unrestricted/Linear.hs, src/Prelude/Linear.hs
A more fine grained linear num hierarchy.
=> Linear num typeclasses

src/Control/Monad/Linear.hs, src/Control/Monad/Linear/Internal.hs
Adds linear reader and state monad transformers, and a monad transformer class.
=> Linear monad transformers

src/Data/Array/Destination.hs
=> Write mirror in terms of fromFunction

src/Data/Vector/Linear.hs
Avoid some uses of `Unsafe.coerce`, and re-organise others.
=> Some cleanups in vectors of known length

src/Control/Optics/Linear/Internal.hs
Give a weaker constraint for `lengthOf`.
=> Weaken constraint for lengthOf

linear-base.cabal, shell.nix, stack.yaml, test/Spec.hs, test/Test/Data/Mutable/Array.hs, test/Test/Data/Mutable/HashMap.hs, test/Test/Data/Mutable/Vector.hs
I reviewed Hedgehog and Quickcheck and chose the former. Setting it up was a bit messy since various combinations of `hedgehog` and `constraints` didn't like each other. (I think this is ultimately because of stack's allow-newer but I'm not sure.)
In any case, just got it working now.
=> Setup done -- phew!

linear-base.cabal, src/Data/HashMap/Linear.hs, src/Data/Set/Mutable/Linear.hs, test/Spec.hs, test/Test/Data/Mutable/Set.hs
I added mutable sets in the style of the arrays, vectors and hashmaps.
=> Added mutable sets & axiomatic property tests

linear-base.cabal, src/Control/Monad/Builder.hs, src/Control/Monad/Linear.hs, src/Control/Monad/Linear/Builder.hs, src/Control/Monad/Linear/Internal.hs, src/Data/Array/Mutable/Linear.hs, src/Data/Bifunctor/Linear.hs, src/Data/Functor/Linear.hs, src/Data/Functor/Linear/Internal.hs, src/Data/Functor/Linear/Internal/Traversable.hs, src/Data/HashMap/Linear.hs, src/Data/Monoid/Linear.hs, src/Data/Num/Linear.hs, src/Data/Profunctor/Kleisli/Linear.hs, src/Data/Unrestricted/Linear.hs, src/Data/Vector/Linear.hs, src/Data/Vector/Mutable/Linear.hs, src/Foreign/Marshal/Pure.hs, src/Prelude/Linear.hs, src/System/IO/Linear.hs, src/System/IO/Resource.hs, src/Unsafe/Linear.hs, src/Unsafe/MutableArray.hs
I've gotten through a first pass at module level documentation.
Things I haven't gotten to yet (partly due to time, partly due to me needing to learn a few things to figure out what's going on):
(Italics means it's a public module.)
* Control
* *Optics.Linear.Internal.hs*
* Monad
* *Linear.hs*
* Linear
* Internal.hs
* Data
* Profunctor
* *Linear.hs*
* Kleisli
* *Linear.hs*
* Array:
* *Polarized.hs*
* *Push.hs*
* *Pull.hs*
* *Destination.hs*
=> First Pass at Module-Level Documentation

linear-base.cabal, src/Data/Bool/Linear.hs, src/Data/Either/Linear.hs, src/Data/Eq/Linear.hs, src/Data/Maybe/Linear.hs, src/Data/Ord/Linear.hs, src/Data/Tuple/Linear.hs, src/Prelude/Linear.hs, src/Prelude/Linear/Internal/Simple.hs, stack.yaml
I'm getting a head start on some of the analogs from base that we need.
I made a few minor design choices that I hope are straightforward :)
=> A few simple analogs from base

README.md
Making a PR for notifications.
=> Fixing CI badge url

nixpkgs.nix, shell-stack.nix, shell.nix, src/Data/Bifunctor/Linear.hs, src/Data/Profunctor/Linear.hs, src/Data/Vector/Linear.hs, src/Foreign/Marshal/Pure.hs, src/Prelude/Linear.hs, stack.yaml
Use 'FUN' from GHC.Exts
Instead of 'a -->.(p) b' we now have 'FUN p a b'
=> fix: deprecated '-->.' notation

README.md
=> Update the stack setup in the README

README.md, examples/Simple/TopSort.hs, linear-base.cabal, nixpkgs.nix, shell-stack.nix, shell.nix, src/Data/Bifunctor/Linear.hs, src/Data/HashMap/Linear.hs, src/Data/Profunctor/Linear.hs, src/Data/Vector/Linear.hs, src/Foreign/Marshal/Pure.hs, src/Prelude/Linear.hs, src/Prelude/Linear/Internal/Simple.hs, stack.yaml, test/Test/Data/Mutable/HashMap.hs
A few things from the zurihac talk.
=> Zurihac work

docs/USER_GUIDE.md, examples/README.md
Just for keeping things complete. @feuerbach asked some questions that made me realize a a minimal user guide is probably a good idea.
=> Started a minimal user guide

src/Data/Array/Mutable/Linear.hs, src/Data/Vector/Mutable/Linear.hs, src/Unsafe/MutableArray.hs, test/Test/Data/Mutable/Array.hs, test/Test/Data/Mutable/Vector.hs
Closes #149.
This PR relaxes the precondition that `Unsafe.MutableArray`, `Data.Array.Mutable.Linear` and `Data.Vector.Mutable.Linear` collections should contain at least one element inside to allowing them to contain zero or more elements.
Also, it removes the `resizeMutArr` function on `Unsafe.MutableArray` where it was using the first element when growing an array.  Now it is replaced by `resizeMutArrSeed`, which takes an explicit default value. This is an API change, however I do not think we try to preserve backwards compatibility yet.
Tests seem to be happy, and I added a new case testing `snoc` on an empty vector. 
This PR depends on #152 , so we should merge that one first. It also means that GitHub includes those changes in the diff view, so you might want to only look at the …
=> Allow zero length mutable arrays and vectors

docs/USER_GUIDE.md
A couple of fixes in the User Guide. I'm going to merge immediately just so that I have permalinks for a blog post.
=> User guide mini-fixes

src/Data/Eq/Linear.hs, src/Data/Ord/Linear.hs
I found these instances on `linear-base`:
```haskell
-- This is sound because we consume all parts of a data type when we inspect
-- for equality
instance Ur.Eq a => Eq a where
(==) = Unsafe.toLinear2 (Ur.==)
-- Note: the reason we coerce the unrestricted implementation
-- is because it's optimized for many base types
instance (Dupable a, Ur.Ord a) => Ord a where
(<) = Unsafe.toLinear2 (Ur.<)
(>) = Unsafe.toLinear2 (Ur.>)
(>=) = Unsafe.toLinear2 (Ur.>=)
(<=) = Unsafe.toLinear2 (Ur.<=)
```
However, despite the comments, I fail to see how they are sound; we can not just assume that `Ur.Eq` and `Ur.Ord` instances linearly consume the values. For example, the `Eq` instance allows this:
```haskell
unsafeConsume :: a #-> a #-> ()
unsafeConsume a b = consume (AlwaysEqual a == AlwaysEqual b) …
```
=> Remove unsound Eq and Ord instances

docs/DESIGN.md
=> Documenting how Prelude.Linear.Internal works

src/Data/HashMap/Linear.hs
Previously, this function was implemented with a Unsafe.toLinear call. That wasn't ideal, and on top of that I saw a strange test failure:
```    intersectionWith reference:                               FAIL (0.57s)
✗ intersectionWith reference failed at test/Test/Data/Mutable/HashMap.hs:321:17
after 52 tests and 51 shrinks.
┏━━ test/Test/Data/Mutable/HashMap.hs ━━━
305 ┃ refIntersectionWith :: Property
306 ┃ refIntersectionWith = defProperty $ do
307 ┃   xs <- forAll keyVals
┃   │ￔ [ ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 7 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( -1 , "aaa" )
┃   │ￔ ]
308 ┃   ys <- forAll keyVals
┃   │ￔ [ ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃   │ￔ , ( 0 , "aaa" )
┃ …
```
=> Implement HashMap.intersectionWith safely

src/Control/Optics/Linear/Internal.hs
For reasons unknown, and almost certainly my fault, the order of the
type arguments of optic types (lens, traversal, …) was not the same as
in the lens library.
Even if I had a reason at the time (though I suspect it's just a
mistake), it couldn't have been strong enough to overcome the
principle of least surprise of being compatible with a well-used
package.
This will probably imply something for #108 .
=> Change the parameter order for optics

src/Control/Optics/Linear/Internal.hs, src/Control/Optics/Linear/Traversal.hs, src/Data/Profunctor/Kleisli/Linear.hs, src/Data/Profunctor/Linear.hs
I'm assuming, here, that traversals are built from the same type as
`Traverse`. I believe this to be the right type, which I explain in
some details in #220.
Depends on  #219 #221 .
=> Add a function to create traversals

src/Data/Array/Destination.hs
This replaces #110 but takes much of the comments from there. The examples all typecheck but doctest isn't working with me so I'm leaving that to @utdemir to choose if he wants to fix as he reviews.
=> Documenting destination arrays

src/Data/Array/Destination.hs
Closes #239.
This PR adds a `HasCallStack` constraints to `fill` and `mirror` functions of destination arrays. 
Instead of having variant of `Vector.!` with `HasCallStack` (which'd probably require bounds checking), we do an initial check and panic if the given vector is smaller than the destination array.
I also added a `size` function of `DArray`'s, and made it a part of the public interface; because I did not see a reason not to.
=> Add call stacks to partial functions of destination arrays

examples/Simple/Quicksort.hs, examples/Spec.hs, linear-base.cabal
The quicksort example used in the blog post. Will update the blog post after this is in.
=> quicksort example

test/Test/Data/Mutable/Array.hs, test/Test/Data/Mutable/HashMap.hs, test/Test/Data/Mutable/Vector.hs
In the style of #263 these are the remaining tests we need to fully specify mutable arrays and vectors.
=> Axiomatic tests/vec arr

src/Data/HashMap/Mutable/Linear.hs, test/Test/Data/Mutable/HashMap.hs
In the style of #265, here are the other tests for hashmaps.
I found a bug in `mapMaybeWithKey` and rewrote it hopefully with the same complexity and more readability. The bug was identified with the test `refMap`; it appears `mapMaybeWithKey` lets the map be applied twice to elements with key 0.
It's easy to see why my algorithm is correct and terminates but not so easy to see why it's O(n), though I conjecture that it is and with some hand-waving, it seems probable.
Also, along with the other two PRs, this closes #93.
=> Axiomatic hashmap tests

linear-base.cabal, src/Control/Functor/Linear.hs, src/Control/Functor/Linear/Internal/Class.hs, src/Control/Functor/Linear/Internal/Instances.hs, src/Control/Functor/Linear/Internal/MonadTrans.hs, src/Control/Functor/Linear/Internal/Reader.hs, src/Control/Functor/Linear/Internal/State.hs, src/Data/Bifunctor/Linear.hs, src/Data/Bifunctor/Linear/Internal/Bifunctor.hs, src/Data/Bifunctor/Linear/Internal/SymmetricMonoidal.hs, src/Data/Functor/Linear.hs, src/Data/Functor/Linear/Internal/Applicative.hs, src/Data/Functor/Linear/Internal/Functor.hs, src/Data/Functor/Linear/Internal/Traversable.hs, src/Data/Unrestricted/Internal/Dupable.hs, src/Data/Unrestricted/Internal/Instances.hs, src/Data/V/Linear.hs, src/Data/V/Linear/Internal/V.hs
=> Module rename: Internal.Linear => Linear.Internal

CHANGELOG.md, README.md, docs/USER_GUIDE.md, linear-base.cabal
Minor updates that we found before we publish the initial release to Hackage.
=> Pre-release updates

README.md
I took the opportunity to remove a rogue timestamp in a Youtube
link. And also a tiny bit of typographic pedantry.
=> README: more talks

src/Data/Unrestricted/Internal/Movable.hs, src/Data/Unrestricted/Internal/Ur.hs
These are tiny cosmetic fixes.
=> Fix rendering of examples in Data.Unrestricted.Linear

docs/USER_GUIDE.md
=> Note that 9.2 fixes linear case

src/Data/Array/Polarized/Push.hs
I made myself a note to add a comment since there was some added clarifying discussion on issue #80.
=> Developer comment for push arrays

src/Data/Unrestricted/Internal/Instances.hs
=> Add Consumable and Dupable instances to V

src/Data/Bifunctor/Linear/Internal/Bifunctor.hs, src/Data/Bifunctor/Linear/Internal/SymmetricMonoidal.hs, src/Data/Monoid/Linear/Internal/Monoid.hs, src/Data/Monoid/Linear/Internal/Semigroup.hs, src/Data/Ord/Linear/Internal/Eq.hs, src/Data/Ord/Linear/Internal/Ord.hs, src/Data/Unrestricted/Internal/Dupable.hs, src/Data/Unrestricted/Internal/Instances.hs, src/Data/Unrestricted/Internal/Movable.hs, src/Data/Unrestricted/Internal/Ur.hs, src/Data/V/Linear/Internal/Instances.hs, src/Data/V/Linear/Internal/V.hs
Closes #321.
We had some internal modules with Haddocks generated, this PR hides them.
=> Hide haddocks on remaining internal modules

bench/Data/Mutable/Array.hs, src/Data/Array/Mutable/Unlifted/Linear.hs
This PR implements `map` function in the PR in a simpler way, directly on top of `Array#`'s. It's as fast as the `map` function on `Data.Vector` now.
In order to be able to measure the results, I also split up a benchmark using `map` and `toList` to two benchmarks each testing a single function.
Without `{-# NOINLINE map #-}` our benchmarks improve a bit. However, I'm keeping it as per the discussion around https://github.com/tweag/linear-base/pull/187#discussion_r489204108. 
Related: https://github.com/tweag/linear-base/issues/328
=> Optimize Data.Array.Mutable.Unlifted.Linear.map

src/Prelude/Linear/Internal.hs
Make some prelude basics representation polymorphic.
=> Representation polymorphism

src/Control/Functor/Linear/Internal/Kan.hs
Not the best explanation I've ever written, but a lot of this
has fallen out of my cache and it is quite confusing to begin
with.
=> A bit of Curried documentation

CHANGELOG.md
I had been a bit too eager to use Github's automerge. in #432.
=> Add review comment to the changelog

CHANGELOG.md, cabal.project, linear-base.cabal
I've already uploaded the candidate, and everything looks in order.
=> Release 0.4.0

src/Data/Unrestricted/Linear.hs
Fixes #476.
@tomjaguarpaw does this look good?
=> Improve wording about Ur

.github/workflows/ci.yaml, nix/sources.json
This required no change (beyond https://github.com/linear-generics/linear-generics/pull/31 , which itself required no change. Very smooth release).
=> CI: Test with GHC 9.12
